In [1]:
import pandas as pd
import numpy as np
import operator
from collections import defaultdict

In [3]:
df = pd.read_csv(open('../data/processed.csv'), low_memory=False)
df.count()

ParserError: Error tokenizing data. C error: out of memory

In [4]:
df = df.dropna(axis=0)
df = df.reset_index(drop=True)
print('有{}筆對話'.format(len(df)))

NameError: name 'df' is not defined

In [4]:
df.head(10)

from                                 to  \
0  ud4097fbb4471c8c54512814bf0182e03  u84fa1e46e99df373e0f978c2ba274f9a   
1  ud4097fbb4471c8c54512814bf0182e03  u96e826dccd3c9db56d684a5ddffc3154   
2  u96e826dccd3c9db56d684a5ddffc3154  ud4097fbb4471c8c54512814bf0182e03   
3  ud4097fbb4471c8c54512814bf0182e03  u96e826dccd3c9db56d684a5ddffc3154   
4  u96e826dccd3c9db56d684a5ddffc3154  ud4097fbb4471c8c54512814bf0182e03   
5  u96e826dccd3c9db56d684a5ddffc3154  ud4097fbb4471c8c54512814bf0182e03   
6  ud4097fbb4471c8c54512814bf0182e03  u96e826dccd3c9db56d684a5ddffc3154   
7  u96e826dccd3c9db56d684a5ddffc3154  ud4097fbb4471c8c54512814bf0182e03   
8  ud4097fbb4471c8c54512814bf0182e03  u96e826dccd3c9db56d684a5ddffc3154   
9  u96e826dccd3c9db56d684a5ddffc3154  ud4097fbb4471c8c54512814bf0182e03   

          text                                  room          time  
0           wd  8aee77a7-1d90-4d0f-b3c3-3f7b94a90e36  1.471640e+12  
1           嗨嗨  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
2           蛤？  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
3   你是第二個使用者ＱＱ  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
4      哈哈哈哈哈哈哈  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
5       這是限定版嗎  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
6       什麼限定版？  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
7         賴限定？  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
8  等我睡醒再來寫fb版本  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12  
9        賴才能用？  fe214cfc-22d1-4736-92e7-d133190142b8  1.471643e+12

In [5]:
df.count()

from    28275265
to      28275265
text    28275265
room    28275265
time    28275265
dtype: int64

## Groupby by 'from' column 

In [5]:
grouped_data = df.groupby('from')['text'].apply(list).reset_index()
print('have {} users'.format(len(grouped_data)))

have 52703 users


In [7]:
# df.loc[df['from'] == 'ud4097fbb4471c8c54512814bf0182e03']

In [6]:
grouped_data.head()
# type(grouped_data.text[0])

from                                      text
0  100000074540167  [Udf65fb966d9b628dd5b7e88569af4339/屢勸不聽]
1  100000286958812                             [哈哈哈, 一秒也太誇張]
2  100002516292141                        [因為還沒上大學 不知道以後會怎樣]
3  100002919027218                                       [嗎]
4  100003139568226                [哈嘍, 我正在吃😂, 你是大學生嗎, 安安, .]

In [7]:
print('id為 {} 的使用者傳送的訊息 ：{}'.format(grouped_data.iloc[0][0],grouped_data.iloc[0][1]))

id為 100000074540167 的使用者傳送的訊息 ：['Udf65fb966d9b628dd5b7e88569af4339/屢勸不聽']


In [ ]:
fileTrainSeg = []

In [ ]:
for i in range((len(df))):
    seglist = jieba.cut(df['text'][i])  
#     print(" ".join(seglist))
    fileTrainSeg.append([" ".join(list(jieba.cut(df['text'][i])))])

In [ ]:
fileSegWordDonePath ='../data/seperate_done.txt'
with open(fileSegWordDonePath,'w') as fW:
    for i in range(len(fileTrainSeg)):
        fW.write(fileTrainSeg[i][0])
        fW.write('\n')

## 載入分詞檔做訓練

In [ ]:
from gensim.models import word2vec
import logging

def vec():

    logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
    sentences = word2vec.Text8Corpus("../data/seperate_done.txt")
    model = word2vec.Word2Vec(sentences, size=10, window=5, min_count=5, workers=1)
    
    model.init_sims(replace=True)

    # Save our model.
    model.save("../data/corpusModel.bin")


    # To load a model.
    # model = word2vec.Word2Vec.load("your_model.bin")
    
vec()

In [9]:
model = word2vec.Word2Vec.load("../data/corpusModel.bin")

Starting training using file ../data/corpusSegDone.txt
Vocab size: 140924
Words in train file: 146129268


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [19]:
model.wv['電腦']

array([-0.52069503, -0.6918993 , -0.13431406,  0.48177987], dtype=float32)

## 設定停用詞

In [11]:
import jieba
import jieba.posseg as pseg
import jieba.analyse

stopwordset = set()
with open('jieba_txt/stop_words.txt','r',encoding='utf-8') as sw:
    for line in sw:
        stopwordset.add(line.strip('\n'))
        
chars = set(' abcdefghijklmnopqrstuvwxyz0123456789()?@？!$,~:.。，-_&=/􀆿\r\n')
for c in chars:
    stopwordset.add(c)

In [12]:
# stopwordset

In [13]:
length = len(grouped_data)
length

52703

In [22]:
top10_vector = np.zeros(shape=(length,10))
jieba.set_dictionary('jieba_txt/dict.txt.big.txt')
jieba.load_userdict("jieba_txt/userdict.txt")

logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

for i in range(length):
    frequency = defaultdict(int)
    for j in range(len(grouped_data.iloc[i][1])):
        seglist = jieba.cut((grouped_data.iloc[i][1])[j])
        texts = [word for word in seglist if word not in stopwordset]
        for text in texts:
            frequency[text] += 1
            
    a = sorted(frequency.items(), key=operator.itemgetter(1),reverse=True)
    row = np.zeros(shape=(1,10))
    r = 10 if len(a) >= 10 else len(a)
    
    if i%100 ==0 :
        print(i)
        
    for x in range(r):
        if a[x][0] in model:
            show = float(model[a[x][0]])
            row[0][x] = show
    top10_vector[i] = row

Building prefix dict from /home/tp6han/gp_new/jieba_txt/dict.txt.big.txt ...
2017-12-18 15:59:26,826 : DEBUG : Building prefix dict from /home/tp6han/gp_new/jieba_txt/dict.txt.big.txt ...
Loading model from cache /tmp/jieba.u0ddb98113e9461fac3a7658d9e24e45e.cache
2017-12-18 15:59:26,828 : DEBUG : Loading model from cache /tmp/jieba.u0ddb98113e9461fac3a7658d9e24e45e.cache
Loading model cost 1.558 seconds.
2017-12-18 15:59:28,386 : DEBUG : Loading model cost 1.558 seconds.
Prefix dict has been built succesfully.
2017-12-18 15:59:28,388 : DEBUG : Prefix dict has been built succesfully.


0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18

In [23]:
top10_vector.shape

(52703, 10)

In [25]:
top10_vector[1]

array([ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
model.corpus_count

11708

# k-means clustering

In [40]:
from sklearn import cluster, datasets

# KMeans 演算法
kmeans_fit = cluster.KMeans(n_clusters = 3,random_state=1170).fit(top10_vector)

# 印出分群結果
cluster_labels = kmeans_fit.labels_
print("分群結果 前10：")
print(cluster_labels[:10])
print("---")

分群結果 前10：
[0 0 0 0 0 0 0 0 0 0]
---


In [41]:
len(cluster_labels)

5402

In [42]:
unique, counts = np.unique(cluster_labels, return_counts=True)
dict(zip(unique, counts))

{0: 4769, 1: 274, 2: 359}

In [43]:
cluster_done = grouped_data
cluster_done['category'] = cluster_labels

In [44]:
cluster_done = cluster_done.sort_values(by='category')
# t = t.drop('from',1)

In [45]:
cluster_done = cluster_done.reset_index(drop=True)
cluster_done.head()

from                                               text  \
0  1000309370066644  [嘿, 哈哈, 爽賺一天假, 你沒放哦, 額真假, 為什麼, 哈哈哈哈哈, 不一樣啦, 我才...   
1         273860868  [你好, 你好啊, 你在幹嘛呀0..0, 我都躲在家了, 香港人哦餓, 哈哈, 颱風天好無聊...   
2         273826628  [開發者速速現, 沒關係, 聽說開發者是帥哥, 寶傑你怎麼看, 哈哈阿哈哈, 我是女生, 寶...   
3         273624498  [嗨, 高雄, 沒欸 你有喔, ......, 啊你哪裡, 還好?, 欸哈哈哈哈, 我要跟你...   
4         273025952  [摸我自己不行喔  我有你沒有的哈哈哈, 知  男  而  退, 我曾經夢到我被警察強吻耶😂...   

   category  
0         0  
1         0  
2         0  
3         0  
4         0

In [46]:
cluster_done.count()
# small_clustered = cluster_done[6000:6300].reset_index(drop=True)

from        5402
text        5402
category    5402
dtype: int64

In [47]:
cluster_done.to_csv('../data/k_means_result2.csv',encoding='utf-8-sig',index=False)

## make dictionary = { from : category }

In [24]:
from_category = {}
for i, row in cluster_done.iterrows():
    from_category[row['from']] = row['category']

In [25]:
len(from_category)

12691

## groupby room 

In [27]:
df2 = df.copy()
df2 = df2.drop(['time','to'], axis=1)

In [28]:
df2['category'] = df2['from'].map(from_category)

In [29]:
df2.head()
df2 = df2.dropna(axis=0)
df2.count()


from        999961
text        999961
room        999961
category    999961
dtype: int64

In [30]:
df2.head()

from        text  \
0  ud4097fbb4471c8c54512814bf0182e03          wd   
1  ud4097fbb4471c8c54512814bf0182e03          嗨嗨   
2  u96e826dccd3c9db56d684a5ddffc3154          蛤？   
3  ud4097fbb4471c8c54512814bf0182e03  你是第二個使用者ＱＱ   
4  u96e826dccd3c9db56d684a5ddffc3154     哈哈哈哈哈哈哈   

                                   room  category  
0  8aee77a7-1d90-4d0f-b3c3-3f7b94a90e36         1  
1  fe214cfc-22d1-4736-92e7-d133190142b8         1  
2  fe214cfc-22d1-4736-92e7-d133190142b8         1  
3  fe214cfc-22d1-4736-92e7-d133190142b8         1  
4  fe214cfc-22d1-4736-92e7-d133190142b8         1

In [84]:
p1 = df2.groupby('room')['from'].aggregate(lambda x: set(x)).reset_index()
p2 = df2.groupby('room')['category'].aggregate(lambda x: set(x)).reset_index()
c = df2.groupby('room')['text'].agg(['count']).reset_index()
t = df2.groupby('room')['text'].apply(list).reset_index()

In [32]:
print('have {} {} rooms'.format(len(p1),len(p2)))

have 39423 39423 rooms


## new df  group by room

In [85]:
room_grouped = pd.concat([p1,p2['category'],c['count'],t['text']],axis=1)

In [86]:
room_grouped.columns

Index(['room', 'from', 'category', 'count', 'text'], dtype='object')

In [87]:
room_grouped.head()

room  \
0  0000d3d1-cd74-4c6a-8ab6-8c9c0df594aa   
1  000129e0-e9c9-4e51-8b7a-b782d220894e   
2  0002fc8b-0951-47b0-9348-bf7decae9d93   
3  000418d0-779f-469a-ad5b-7fcfd6da4959   
4  00054188-59bc-49cf-aea2-e8ddd7057849   

                                                from category  count  \
0  {1313316695368083, u84ff3587ce973343ca6328d688...      {2}      2   
1                                 {1127853807261849}      {1}      1   
2                 {955305891265054, 966587086804396}   {1, 2}      6   
3  {ua725d2fbddf188fb2e97f67bbd36d056, 1084323831...      {1}     26   
4               {1192735997454971, 1157361747619580}      {1}    162   

                                                text  
0                                        [嗨嗨, 请问有人吗]  
1                                                [安]  
2                     [嗨, 你好喔, 你好喔~, 男生, 你呢, me too]  
3  [你好, 嗨, 嗨, 男, 女, 住哪呀?, 高雄, 台中, 那多大, 18\n你呢, 21...  
4  [妳好, 你好啊阿, 真假的, 這真的很酷, 假的, 迪卡上看到的嗎, 對啊, 你是我第一個...

## delete the row (room) which has only one user 

In [88]:
for index, row in room_grouped.iterrows():
    l = len(row['from'])
    if l == 1 :
        room_grouped.drop(index, inplace=True)

In [89]:
room_grouped.count()

room        30535
from        30535
category    30535
count       30535
text        30535
dtype: int64

In [90]:
room_grouped.head()

room  \
0  0000d3d1-cd74-4c6a-8ab6-8c9c0df594aa   
2  0002fc8b-0951-47b0-9348-bf7decae9d93   
3  000418d0-779f-469a-ad5b-7fcfd6da4959   
4  00054188-59bc-49cf-aea2-e8ddd7057849   
5  0005ce30-1ab7-4b4f-8861-684a88e4f94b   

                                                from category  count  \
0  {1313316695368083, u84ff3587ce973343ca6328d688...      {2}      2   
2                 {955305891265054, 966587086804396}   {1, 2}      6   
3  {ua725d2fbddf188fb2e97f67bbd36d056, 1084323831...      {1}     26   
4               {1192735997454971, 1157361747619580}      {1}    162   
5                {1020089304775462, 954276064700164}      {1}    175   

                                                text  
0                                        [嗨嗨, 请问有人吗]  
2                     [嗨, 你好喔, 你好喔~, 男生, 你呢, me too]  
3  [你好, 嗨, 嗨, 男, 女, 住哪呀?, 高雄, 台中, 那多大, 18\n你呢, 21...  
4  [妳好, 你好啊阿, 真假的, 這真的很酷, 假的, 迪卡上看到的嗎, 對啊, 你是我第一個...  
5  [我不給ㄩ, 我也沒ㄩ你啊, 到處都是什麼霸主的, 那是什麼, 晚上一直聽到, 不知道, 感...

### 每間聊天室平均聊幾句

In [98]:
room_grouped['count'].mean()

32.296905190764697

# 證明分群有意義

## 1. 同一群的使用者平均聊天句數比不同群的使用者平均聊天句數還多

In [117]:
same_cat_count = 0
all_text = 0
other_user = 0
other_all_text = 0
for index, row in room_grouped.iterrows():
    l = len(row['category'])
    t_len = len(row['text'])
# same cluster
    if l == 1:
        same_cat_count+=1
        all_text+=t_len
# different cluster
    else:
        other_user+=1
        other_all_text+=t_len

In [118]:
print('同一群的使用者有 {} 組, 平均聊天句數 : {}'.format(same_cat_count,all_text/same_cat_count))
print('不同群的使用者有 {} 組, 平均聊天句數 : {}'.format(other_user ,other_all_text/other_user))

同一群的使用者有 18187 組, 平均聊天句數 : 41.353164348160774
不同群的使用者有 12348 組, 平均聊天句數 : 18.95821185617104


## 2. 聊天句數超過 1000 句的使用者，同群的有幾組

In [123]:
gt1000 = room_grouped[room_grouped['count']>1000]

In [124]:
gt1000_same_cat = 0
for i, row in temp.iterrows():
    l = len(row['category'])
    if l == 1:
        gt1000_same_cat+=1

In [125]:
print('共有 {} 組，同類的有 {} 組'.format(len(gt1000),gt1000_same_cat))

共有 29 組，同類的有 26 組


In [105]:
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
t.to_csv('../data/k_means_result.csv',encoding='utf-8-sig')