In [1]:
import pandas as pd
import numpy as np
import operator
from collections import defaultdict

In [4]:
df = pd.read_csv(open('../data/processed.csv'), low_memory=False)
df = df[df['text'].str.contains("00leave")== False]

df = df.dropna(axis=0)
# df = df.drop('Unnamed: 0', 1)
print('有{}筆對話'.format(len(df)))

ValueError: labels ['Unnamed: 0'] not contained in axis

In [5]:
print('有{}筆對話'.format(len(df)))

有28275265筆對話


In [8]:
df2 = df.copy()

In [ ]:
df = df[df['text'].str.contains("00add")== False]

In [11]:
df = df.reset_index(drop=True)

In [10]:
df.count()

from    28275265
to      28275265
text    28275265
room    28275265
time    28275265
dtype: int64

In [13]:
df =df.head(100000)

## Groupby by 'from' column 

In [14]:
grouped_data = df.groupby('from')['text'].apply(list).reset_index()
print('have {} users'.format(len(grouped_data)))

have 1089 users


In [ ]:
# df.loc[df['from'] == 'ud4097fbb4471c8c54512814bf0182e03']

In [15]:
grouped_data.head()
# type(grouped_data.text[0])

from                                               text
0  1000970273334199  [找不到阿, 安安, 你有打LOL嗎, 好吧，可以帶我嗎, 安安, 凸, Sor, 嗯, 約...
1  1001070263323689  [!?, 唐寶寶, 你那麼愛慕他ㄇ, 嗨, 先問問您期望本人的性別是?, 了解, 我是男的,...
2  1001967239901904  [早, 在床上發懶, 爆, 斷, 魂, 你在暗諷綠藻嘛, 壞, 話說我好餓ㄛ, 窩不要這個q...
3  1003172849781848  [甲, 你要做我的0？, 人生勝利組是不會來玩這個的, 你一定不是c銘, 也不是業王, 葉你...
4  1003929993039131  [吃噓, 肥宅早, 我們不是場外人, 場外ㄈㄓ, 我沒用了, 安安, 是喔, 場外ㄈㄓ嗎, ...

In [16]:
print('id為 {} 的使用者傳送的訊息 ：{}'.format(grouped_data.iloc[0][0],grouped_data.iloc[0][1]))

id為 1000970273334199 的使用者傳送的訊息 ：['找不到阿', '安安', '你有打LOL嗎', '好吧，可以帶我嗎', '安安', '凸', 'Sor', '嗯', '約哪', '有啊', '你先約的啊', '喔', '我懶的打了', '皮米屌', '這你嗎？', '魏癢癢', '哪裡人?', '住哪裡啦？', '超癢', '哪裡人?', '好遠', '其實還好', '新竹', '龍潭?', 'ㄏㄅㄨㄐㄅㄌㄗㄋ', '三小', '幹又ㄋ', '掰掰', '凹?', '凸sor']


## set stop word

In [36]:
import jieba
import jieba.posseg as pseg
import jieba.analyse

stopwordset = set()
with open('jieba_txt/stop_words.txt','r',encoding='utf-8') as sw:
    for line in sw:
        stopwordset.add(line.strip('\n'))
        
chars = set(' abcdefghijklmnopqrstuvwxyz0123456789()?@？!$,~:.。，-_&=/􀆿\r\n')
for c in chars:
    stopwordset.add(c)

In [22]:
import logging
import jieba

In [91]:
fileTrainSeg = []

In [92]:
for i in range((len(df))):
    seglist = jieba.cut(df['text'][i])  
#     print(" ".join(seglist))
    fileTrainSeg.append([" ".join(list(jieba.cut(df['text'][i])))])

In [94]:
fileSegWordDonePath ='../data/seperate_done.txt'
with open(fileSegWordDonePath,'w') as fW:
    for i in range(len(fileTrainSeg)):
        fW.write(fileTrainSeg[i][0])
        fW.write('\n')

## 載入分詞檔做訓練

In [95]:
from gensim.models import word2vec
import logging

def vec():

    logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
    sentences = word2vec.Text8Corpus("../data/seperate_done.txt")
    model = word2vec.Word2Vec(sentences, size=10)

    # Save our model.
    model.save("med250.model.bin")

    # To load a model.
    # model = word2vec.Word2Vec.load("your_model.bin")
    
vec()

2017-12-23 03:03:53,308 : INFO : 'pattern' package not found; tag filters are not available for English
2017-12-23 03:03:53,313 : WARNING : consider setting layer size to a multiple of 4 for greater performance
2017-12-23 03:03:53,313 : INFO : collecting all words and their counts
2017-12-23 03:03:53,316 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2017-12-23 03:03:53,454 : INFO : collected 25918 word types from a corpus of 378621 raw words and 38 sentences
2017-12-23 03:03:53,455 : INFO : Loading a fresh vocabulary
2017-12-23 03:03:53,481 : INFO : min_count=5 retains 4650 unique words (17% of original 25918, drops 21268)
2017-12-23 03:03:53,482 : INFO : min_count=5 leaves 336751 word corpus (88% of original 378621, drops 41870)
2017-12-23 03:03:53,502 : INFO : deleting the raw counts dictionary of 25918 items
2017-12-23 03:03:53,504 : INFO : sample=0.001 downsamples 65 most-common words
2017-12-23 03:03:53,505 : INFO : downsampling leaves estimated 255024

In [15]:
# from gensim import models
# import gensim
# sentences = models.word2vec.LineSentence("../data/small_model.txt")
# model = models.word2vec.Word2Vec(sentences, size=10, window=5, min_count=5, workers=1)

In [96]:
length = len(grouped_data)
length

1089

In [99]:
model = word2vec.Word2Vec.load("med250.model.bin")

2017-12-23 03:05:48,461 : INFO : loading Word2Vec object from med250.model.bin
2017-12-23 03:05:48,475 : INFO : loading wv recursively from med250.model.bin.wv.* with mmap=None
2017-12-23 03:05:48,477 : INFO : setting ignored attribute syn0norm to None
2017-12-23 03:05:48,478 : INFO : setting ignored attribute cum_table to None
2017-12-23 03:05:48,479 : INFO : loaded med250.model.bin


In [102]:
model.wv['我']


array([-1.77673686, -0.01865516, -2.17800283, -0.50967389, -0.63324803,
       -1.28513396, -0.06545687,  0.9026472 , -1.61018419,  0.11806323], dtype=float32)

In [117]:
top10_vector = np.zeros(shape=(length,10))
jieba.set_dictionary('jieba_txt/dict.txt.big.txt')
jieba.load_userdict("jieba_txt/userdict.txt")

for i in range(length):
    frequency = defaultdict(int)
    for j in range(len(grouped_data.iloc[i][1])):
        seglist = jieba.cut((grouped_data.iloc[i][1])[j])
        texts = [word for word in seglist if word not in stopwordset]
        for text in texts:
            frequency[text] += 1
            
    a = sorted(frequency.items(), key=operator.itemgetter(1),reverse=True)
    row = np.zeros(shape=(1,10))
    vec = np.zeros(shape=(10,10))

    r = 10 if len(a) >= 10 else len(a)
    
    for x in range(r):
        if a[x][0] in model:
            show = model.wv[a[x][0]]
#             print(show)
        else:
            show = np.zeros(shape=(1,10))
        vec[x] = show
    top10_vector[i] = np.sum(vec,axis=0)

Building prefix dict from /home/tp6han/gp_new/jieba_txt/dict.txt.big.txt ...
2017-12-23 03:22:12,810 : DEBUG : Building prefix dict from /home/tp6han/gp_new/jieba_txt/dict.txt.big.txt ...
Loading model from cache /tmp/jieba.u0ddb98113e9461fac3a7658d9e24e45e.cache
2017-12-23 03:22:12,812 : DEBUG : Loading model from cache /tmp/jieba.u0ddb98113e9461fac3a7658d9e24e45e.cache
Loading model cost 1.564 seconds.
2017-12-23 03:22:14,376 : DEBUG : Loading model cost 1.564 seconds.
Prefix dict has been built succesfully.
2017-12-23 03:22:14,378 : DEBUG : Prefix dict has been built succesfully.


In [118]:
top10_vector.shape

(1089, 10)

In [121]:
top10_vector[:100]

array([[ -1.55475231e+01,   1.33039861e+00,  -1.67596185e+01,
          1.28056386e+00,  -8.17674989e+00,  -4.66774284e+00,
         -4.85303497e+00,   5.28552514e+00,  -1.76169015e+01,
          1.52367278e+01],
       [ -1.34475759e+01,   9.04911076e-01,  -1.93404279e+01,
         -2.41772740e+00,  -5.60826528e+00,  -1.34217998e+01,
          7.00256024e+00,   6.67532852e+00,  -1.35000029e+01,
          9.47472851e+00],
       [ -1.27298579e+01,   1.67615626e+00,  -1.81523109e+01,
         -3.39368605e+00,  -8.05392225e+00,  -1.38386394e+01,
          2.06732383e+00,   8.43027118e+00,  -1.75969543e+01,
          7.39797142e+00],
       [ -1.27891113e+01,  -2.57086130e-02,  -1.69530688e+01,
         -3.96647520e+00,  -9.27212630e+00,  -1.30951231e+01,
          5.83409508e+00,   8.64753144e+00,  -1.61800740e+01,
          1.05129326e+01],
       [ -1.45905932e+01,   7.64580049e+00,  -7.63335931e+00,
         -4.26557828e+00,  -9.11364672e+00,  -9.26516009e+00,
         -8.09108712e+00

# k-means clustering

In [123]:
from sklearn import cluster, datasets

# KMeans 演算法
kmeans_fit = cluster.KMeans(n_clusters = 3,random_state=1170).fit(top10_vector)

# 印出分群結果
cluster_labels = kmeans_fit.labels_
print("分群結果 前10：")
print(cluster_labels[:10])
print("---")

分群結果 前10：
[2 1 1 1 2 1 1 1 0 1]
---


In [124]:
len(cluster_labels)

1089

In [125]:
unique, counts = np.unique(cluster_labels, return_counts=True)
dict(zip(unique, counts))

{0: 239, 1: 425, 2: 425}

In [126]:
cluster_done = grouped_data
cluster_done['category'] = cluster_labels

In [127]:
cluster_done = cluster_done.sort_values(by='category')
# t = t.drop('from',1)

In [128]:
cluster_done = cluster_done.reset_index(drop=True)
cluster_done.head()

from  \
0                   1209466565772041   
1  u45090d416a11dc11247806b93868c878   
2  u4651015fc4e3c0006c25c6417b4c6708   
3  u465bc401e917e682dacc95f78d48bcb2   
4                   1251358191561599   

                                                text  category  
0                                        [@@, 嘿, 尼哥]         0  
1                         [？？？？？？, 有吧, 好神奇的功能, 你覺得呢]         0  
2                                        [哈囉, 呃, 哈囉]         0  
3  [幹, 如何 要做愛嗎, 我叫王希銘, 借錢要還 誰還要借, 你真的是女生喔= =, 我也是...         0  
4                                               [Hi]         0

In [129]:
cluster_done.count()
# small_clustered = cluster_done[6000:6300].reset_index(drop=True)

from        1089
text        1089
category    1089
dtype: int64

In [130]:
cluster_done.to_csv('../data/k_means_result2.csv',encoding='utf-8-sig',index=False)

## make dictionary = { from : category }

In [131]:
from_category = {}
for i, row in cluster_done.iterrows():
    from_category[row['from']] = row['category']

In [132]:
len(from_category)

1089

## groupby room 

In [133]:
df2 = df.copy()
df2 = df2.drop(['time','to'], axis=1)

In [134]:
df2['category'] = df2['from'].map(from_category)

In [135]:
df2.head()
df2 = df2.dropna(axis=0)
df2.count()


from        100000
text        100000
room        100000
category    100000
dtype: int64

In [136]:
df2.head()

from        text  \
0  ud4097fbb4471c8c54512814bf0182e03          wd   
1  ud4097fbb4471c8c54512814bf0182e03          嗨嗨   
2  u96e826dccd3c9db56d684a5ddffc3154          蛤？   
3  ud4097fbb4471c8c54512814bf0182e03  你是第二個使用者ＱＱ   
4  u96e826dccd3c9db56d684a5ddffc3154     哈哈哈哈哈哈哈   

                                   room  category  
0  8aee77a7-1d90-4d0f-b3c3-3f7b94a90e36         1  
1  fe214cfc-22d1-4736-92e7-d133190142b8         1  
2  fe214cfc-22d1-4736-92e7-d133190142b8         1  
3  fe214cfc-22d1-4736-92e7-d133190142b8         1  
4  fe214cfc-22d1-4736-92e7-d133190142b8         1

In [137]:
p1 = df2.groupby('room')['from'].aggregate(lambda x: set(x)).reset_index()
p2 = df2.groupby('room')['category'].aggregate(lambda x: set(x)).reset_index()
c = df2.groupby('room')['text'].agg(['count']).reset_index()
t = df2.groupby('room')['text'].apply(list).reset_index()

In [138]:
print('have {} {} rooms'.format(len(p1),len(p2)))

have 4580 4580 rooms


## new df  group by room

In [139]:
room_grouped = pd.concat([p1,p2['category'],c['count'],t['text']],axis=1)

In [140]:
room_grouped.columns

Index(['room', 'from', 'category', 'count', 'text'], dtype='object')

In [141]:
room_grouped.head()

room  \
0  0005ce30-1ab7-4b4f-8861-684a88e4f94b   
1  001b9df7-c22b-4f8a-be3a-403aaffb6bf0   
2  0037b4bb-7eab-4edd-ac43-02be91706b6e   
3  0040db15-e65e-4873-8e20-163eedd8c5d6   
4  004cc3ae-22e7-4df5-b24a-1b731db5ac39   

                                                from category  count  \
0                {954276064700164, 1020089304775462}      {1}    175   
1  {u6dbd49530b86288633b4cb1b3deea5be, 1071753506...   {1, 2}     17   
2  {ue71379d634d1bb1046832b7c0a4326f1, u04c05fef9...   {1, 2}     78   
3  {u9d5f483d81a1cc9bc133616d5d916187, ub37a5cdfc...      {2}      4   
4               {1377818128910140, 1269009779778365}      {2}      3   

                                                text  
0  [我不給ㄩ, 我也沒ㄩ你啊, 到處都是什麼霸主的, 那是什麼, 晚上一直聽到, 不知道, 感...  
1  [嗨, 小妹今年12歲><, 我今年15, 是哥哥嗎？, 是呀~, 約嗎, 不約喔~, 能交...  
2  [ㄢㄢ, ㄩㄇ, 登能, ㄩ你老木, 你4誰, 先做愛, 小名如何稱呼, 在問我4誰, 做愛...  
3                                [ㄢㄢ, 安 咩休幹某, 又你, 滾]  
4                               [晚安阿, 那麼晚了，ㄩㄇ, 約浪漫嗎]

## delete the row (room) which has only one user 

In [142]:
for index, row in room_grouped.iterrows():
    l = len(row['from'])
    if l == 1 :
        room_grouped.drop(index, inplace=True)

In [143]:
room_grouped.count()

room        3986
from        3986
category    3986
count       3986
text        3986
dtype: int64

In [144]:
room_grouped.head()

room  \
0  0005ce30-1ab7-4b4f-8861-684a88e4f94b   
1  001b9df7-c22b-4f8a-be3a-403aaffb6bf0   
2  0037b4bb-7eab-4edd-ac43-02be91706b6e   
3  0040db15-e65e-4873-8e20-163eedd8c5d6   
4  004cc3ae-22e7-4df5-b24a-1b731db5ac39   

                                                from category  count  \
0                {954276064700164, 1020089304775462}      {1}    175   
1  {u6dbd49530b86288633b4cb1b3deea5be, 1071753506...   {1, 2}     17   
2  {ue71379d634d1bb1046832b7c0a4326f1, u04c05fef9...   {1, 2}     78   
3  {u9d5f483d81a1cc9bc133616d5d916187, ub37a5cdfc...      {2}      4   
4               {1377818128910140, 1269009779778365}      {2}      3   

                                                text  
0  [我不給ㄩ, 我也沒ㄩ你啊, 到處都是什麼霸主的, 那是什麼, 晚上一直聽到, 不知道, 感...  
1  [嗨, 小妹今年12歲><, 我今年15, 是哥哥嗎？, 是呀~, 約嗎, 不約喔~, 能交...  
2  [ㄢㄢ, ㄩㄇ, 登能, ㄩ你老木, 你4誰, 先做愛, 小名如何稱呼, 在問我4誰, 做愛...  
3                                [ㄢㄢ, 安 咩休幹某, 又你, 滾]  
4                               [晚安阿, 那麼晚了，ㄩㄇ, 約浪漫嗎]

### 每間聊天室平均聊幾句

In [145]:
room_grouped['count'].mean()

24.837932764676367

# 證明分群有意義

## 1. 同一群的使用者平均聊天句數比不同群的使用者平均聊天句數還多

In [146]:
same_cat_count = 0
all_text = 0
other_user = 0
other_all_text = 0
for index, row in room_grouped.iterrows():
    l = len(row['category'])
    t_len = len(row['text'])
# same cluster
    if l == 1:
        same_cat_count+=1
        all_text+=t_len
# different cluster
    else:
        other_user+=1
        other_all_text+=t_len

In [147]:
print('同一群的使用者有 {} 組, 平均聊天句數 : {}'.format(same_cat_count,all_text/same_cat_count))
print('不同群的使用者有 {} 組, 平均聊天句數 : {}'.format(other_user ,other_all_text/other_user))

同一群的使用者有 2022 組, 平均聊天句數 : 27.69634025717112
不同群的使用者有 1964 組, 平均聊天句數 : 21.89511201629328


## 2. 聊天句數超過 1000 句的使用者，同群的有幾組

In [155]:
gt1000 = room_grouped[room_grouped['count']>50]

In [156]:
gt1000_same_cat = 0
for i, row in gt1000.iterrows():
    l = len(row['category'])
    if l == 1:
        gt1000_same_cat+=1

In [157]:
print('共有 {} 組，同類的有 {} 組'.format(len(gt1000),gt1000_same_cat))

共有 412 組，同類的有 231 組


In [158]:
import matplotlib.pyplot as plt
%matplotlib inline

In [22]:
t.to_csv('../data/k_means_result.csv',encoding='utf-8-sig')